# Note: LLD linker configuration only for Linux CI - macOS uses default linker

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "target-cpu=native",      # Optimize for CI runner CPU
]

# Speed up builds by reducing optimization in dependencies
[profile.dev.package."*"]
opt-level = 0
debug = false

# Faster builds for tests and checks
[profile.test]
opt-level = 0
debug = false

# Keep dependencies optimized even in dev
[profile.dev.package.tauri]
opt-level = 2

[profile.dev.package.webkit2gtk-rs]
opt-level = 2

[profile.dev.package.gtk-rs]
opt-level = 2

# Registry optimization
[registries.crates-io]
protocol = "sparse"

# Network optimization
[net]
retry = 2
git-fetch-with-cli = true

# Build cache optimization
[term]
verbose = false