name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'BUILD.md'
      - 'DISTRIBUTION.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate documentation
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs
          
          # Convert markdown files to HTML
          if [ -f "BUILD.md" ]; then
            pandoc BUILD.md -o docs/build-guide.html \
              --template=docs/assets/template.html \
              --css=assets/style.css \
              --css=assets/docs.css \
              --metadata title="Build Guide - Clean RN Dev" \
              --standalone
          fi
          
          if [ -f "DISTRIBUTION.md" ]; then
            pandoc DISTRIBUTION.md -o docs/distribution.html \
              --template=docs/assets/template.html \
              --css=assets/style.css \
              --css=assets/docs.css \
              --metadata title="Distribution Guide - Clean RN Dev" \
              --standalone
          fi

      - name: Create features page
        run: |
          cat > docs/features.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Features - Clean RN Dev</title>
              <link rel="stylesheet" href="assets/style.css">
              <link rel="stylesheet" href="assets/docs.css">
          </head>
          <body>
              <nav class="docs-nav">
                  <div class="container">
                      <a href="index.html" class="nav-logo">
                          <span class="gradient-text">Clean RN Dev</span>
                      </a>
                      <div class="nav-links">
                          <a href="index.html">Home</a>
                          <a href="getting-started.html">Getting Started</a>
                          <a href="build-guide.html">Build Guide</a>
                          <a href="features.html" class="active">Features</a>
                          <a href="https://github.com/seu-usuario/clean-rn-dev">GitHub</a>
                      </div>
                  </div>
              </nav>
              
              <main class="docs-main">
                  <div class="container">
                      <div class="docs-layout">
                          <article class="docs-content">
                              <header class="docs-header">
                                  <h1>🚀 Features Overview</h1>
                                  <p class="docs-subtitle">Complete list of Clean RN Dev features and capabilities</p>
                              </header>
                              
                              <section class="docs-section">
                                  <h2>🧹 Cleaning Capabilities</h2>
                                  <div class="feature-list">
                                      <div class="feature-item">
                                          <h3>📱 React Native & Expo</h3>
                                          <ul>
                                              <li>Expo cache and build artifacts</li>
                                              <li>Metro bundler cache</li>
                                              <li>React Native temp files</li>
                                              <li>Hermes engine cache</li>
                                          </ul>
                                      </div>
                                      
                                      <div class="feature-item">
                                          <h3>🛠️ Development Tools</h3>
                                          <ul>
                                              <li>Xcode DerivedData and caches</li>
                                              <li>Android Gradle and emulator cache</li>
                                              <li>VS Code extensions and logs</li>
                                              <li>Android Studio system files</li>
                                              <li>IntelliJ IDEA caches</li>
                                          </ul>
                                      </div>
                                      
                                      <div class="feature-item">
                                          <h3>📦 Package Managers</h3>
                                          <ul>
                                              <li>npm cache directories</li>
                                              <li>Yarn cache and temp files</li>
                                              <li>pnpm store and cache</li>
                                              <li>CocoaPods repos and cache</li>
                                          </ul>
                                      </div>
                                      
                                      <div class="feature-item">
                                          <h3>🐳 Docker & Containers</h3>
                                          <ul>
                                              <li>Stopped containers</li>
                                              <li>Dangling images</li>
                                              <li>Unused volumes</li>
                                              <li>Build cache</li>
                                          </ul>
                                      </div>
                                      
                                      <div class="feature-item">
                                          <h3>🌐 Browser Caches</h3>
                                          <ul>
                                              <li>Chrome cache and temp files</li>
                                              <li>Firefox cache directories</li>
                                              <li>Safari cache (macOS)</li>
                                              <li>Edge cache (Windows)</li>
                                          </ul>
                                      </div>
                                      
                                      <div class="feature-item">
                                          <h3>🗂️ System Files</h3>
                                          <ul>
                                              <li>System logs and crash reports</li>
                                              <li>Temporary directories</li>
                                              <li>Build artifacts (.apk, .ipa)</li>
                                              <li>Homebrew cache (macOS)</li>
                                          </ul>
                                      </div>
                                  </div>
                              </section>
                              
                              <section class="docs-section">
                                  <h2>⚡ Performance Features</h2>
                                  <ul>
                                      <li><strong>Lightning Fast Scanning:</strong> Multi-threaded Rust backend for maximum speed</li>
                                      <li><strong>Real-time Progress:</strong> Live updates during scanning and cleaning operations</li>
                                      <li><strong>Smart Detection:</strong> Automatically finds cache directories across all platforms</li>
                                      <li><strong>Safe Operations:</strong> Only removes cache files, never touches important data</li>
                                  </ul>
                              </section>
                              
                              <section class="docs-section">
                                  <h2>🎨 User Interface</h2>
                                  <ul>
                                      <li><strong>Modern Design:</strong> Cyberpunk-inspired neon interface</li>
                                      <li><strong>Intuitive Controls:</strong> One-click scanning and cleaning</li>
                                      <li><strong>Detailed Results:</strong> Comprehensive breakdown of found files</li>
                                      <li><strong>System Tray:</strong> Minimize to tray instead of closing</li>
                                  </ul>
                              </section>
                              
                              <section class="docs-section">
                                  <h2>📊 Analytics & History</h2>
                                  <ul>
                                      <li><strong>SQLite Database:</strong> Persistent storage of cleaning history</li>
                                      <li><strong>Detailed Statistics:</strong> Files deleted, space freed, operation duration</li>
                                      <li><strong>Error Tracking:</strong> Complete logs of any issues encountered</li>
                                      <li><strong>Charts & Graphs:</strong> Visual representation of cleaning data</li>
                                  </ul>
                              </section>
                              
                              <div class="docs-navigation">
                                  <a href="getting-started.html" class="nav-prev">← Getting Started</a>
                                  <a href="build-guide.html" class="nav-next">Build Guide →</a>
                              </div>
                          </article>
                      </div>
                  </div>
              </main>
              
              <script src="assets/script.js"></script>
          </body>
          </html>
          EOF

      - name: Create API documentation
        run: |
          cat > docs/api.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>API Reference - Clean RN Dev</title>
              <link rel="stylesheet" href="assets/style.css">
              <link rel="stylesheet" href="assets/docs.css">
          </head>
          <body>
              <nav class="docs-nav">
                  <div class="container">
                      <a href="index.html" class="nav-logo">
                          <span class="gradient-text">Clean RN Dev</span>
                      </a>
                      <div class="nav-links">
                          <a href="index.html">Home</a>
                          <a href="getting-started.html">Getting Started</a>
                          <a href="build-guide.html">Build Guide</a>
                          <a href="features.html">Features</a>
                          <a href="api.html" class="active">API</a>
                          <a href="https://github.com/seu-usuario/clean-rn-dev">GitHub</a>
                      </div>
                  </div>
              </nav>
              
              <main class="docs-main">
                  <div class="container">
                      <div class="docs-layout">
                          <article class="docs-content">
                              <header class="docs-header">
                                  <h1>📡 API Reference</h1>
                                  <p class="docs-subtitle">Tauri commands and interfaces for developers</p>
                              </header>
                              
                              <section class="docs-section">
                                  <h2>🔍 Scanning Commands</h2>
                                  
                                  <div class="api-method">
                                      <h3><code>scan_expo_cache()</code></h3>
                                      <p>Scans for Expo cache files and directories.</p>
                                      <div class="api-details">
                                          <p><strong>Returns:</strong> <code>Result&lt;Vec&lt;ScanResult&gt;, String&gt;</code></p>
                                          <p><strong>Platform:</strong> All</p>
                                      </div>
                                  </div>
                                  
                                  <div class="api-method">
                                      <h3><code>scan_metro_cache()</code></h3>
                                      <p>Scans for Metro bundler cache files.</p>
                                      <div class="api-details">
                                          <p><strong>Returns:</strong> <code>Result&lt;Vec&lt;ScanResult&gt;, String&gt;</code></p>
                                          <p><strong>Platform:</strong> All</p>
                                      </div>
                                  </div>
                                  
                                  <div class="api-method">
                                      <h3><code>scan_docker_cache()</code></h3>
                                      <p>Scans for Docker build cache and unused resources.</p>
                                      <div class="api-details">
                                          <p><strong>Returns:</strong> <code>Result&lt;Vec&lt;ScanResult&gt;, String&gt;</code></p>
                                          <p><strong>Platform:</strong> All (requires Docker)</p>
                                      </div>
                                  </div>
                              </section>
                              
                              <section class="docs-section">
                                  <h2>🧹 Cleaning Commands</h2>
                                  
                                  <div class="api-method">
                                      <h3><code>clean_files(paths: Vec&lt;String&gt;)</code></h3>
                                      <p>Cleans the specified files and directories.</p>
                                      <div class="api-details">
                                          <p><strong>Parameters:</strong></p>
                                          <ul>
                                              <li><code>paths</code> - Array of file/directory paths to clean</li>
                                          </ul>
                                          <p><strong>Returns:</strong> <code>Result&lt;CleaningResult, String&gt;</code></p>
                                      </div>
                                  </div>
                              </section>
                              
                              <section class="docs-section">
                                  <h2>📊 Data Types</h2>
                                  
                                  <div class="api-type">
                                      <h3>ScanResult</h3>
                                      <pre><code>{
    "path": "string",        // File/directory path
    "size": "number",        // Size in bytes
    "file_type": "string",   // Type identifier
    "can_delete": "boolean"  // Whether safe to delete
}</code></pre>
                                  </div>
                                  
                                  <div class="api-type">
                                      <h3>CleaningResult</h3>
                                      <pre><code>{
    "files_deleted": "number", // Number of files removed
    "space_freed": "number",   // Bytes freed
    "duration": "number",      // Operation time (ms)
    "errors": "string[]"       // Any errors encountered
}</code></pre>
                                  </div>
                              </section>
                              
                              <div class="docs-navigation">
                                  <a href="features.html" class="nav-prev">← Features</a>
                                  <a href="https://github.com/seu-usuario/clean-rn-dev" class="nav-next">GitHub Repository →</a>
                              </div>
                          </article>
                      </div>
                  </div>
              </main>
              
              <script src="assets/script.js"></script>
          </body>
          </html>
          EOF

      - name: Update repository URLs
        run: |
          # Get the repository URL from GitHub context
          REPO_URL="https://github.com/${{ github.repository }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          
          # Replace placeholder URLs in all HTML files
          find docs -name "*.html" -type f -exec sed -i "s|seu-usuario/clean-rn-dev|${{ github.repository }}|g" {} \;
          find docs -name "*.html" -type f -exec sed -i "s|seu-usuario.github.io/clean-rn-dev|${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}|g" {} \;
          
          # Update JavaScript API URLs
          sed -i "s|seu-usuario|${REPO_OWNER}|g" docs/assets/script.js
          sed -i "s|clean-rn-dev|${REPO_NAME}|g" docs/assets/script.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4